---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-sentinel
  replicas: 1
  selector:
    matchLabels:
      name: sentinel
  template:
    metadata:
      labels:
        name: sentinel
        redis-sentinel: "true"
#      annotations:
#        security.alpha.kubernetes.io/unsafe-sysctls: net.core.somaxconn=1024
    spec:
      containers:
      - name: redis
        image: cookingcodewithme/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
#        volumeMounts:
#        - mountPath: /redis-master-data
#          name: data
      - name: sentinel
        image: cookingcodewithme/redis:latest
        imagePullPolicy: Always
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
#      volumes:
#        - name: data
#          emptyDir: {}
